apiVersion: v1
kind: Secret
metadata:
  name: sd-db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "password" # Измени на свой
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-db
  labels:
    app: sd-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-db
  template:
    metadata:
      labels:
        app: sd-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        imagePullPolicy: IfNotPresent
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sd-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "service_desk_db"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sd-db-service
spec:
  selector:
    app: sd-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP